{% set version = "3.2.3" %}

package:
  name: xerces-c
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/xerces/c/3/sources/xerces-c-{{ version }}.tar.gz
  sha256: fb96fc49b1fb892d1e64e53a6ada8accf6f0e6d30ce0937956ec68d39bd72c7e
  patches:
    - crosscompilefunctions.patch  # [build_platform != target_platform]

build:
  number: 2
  run_exports:
    # changes SO names at minor rev
    - {{ pin_subpackage('xerces-c', max_pin='x.x') }}

requirements:
  build:
    - perl  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make  # [not win]
    - autoconf  # [build_platform != target_platform]
    - automake  # [build_platform != target_platform]
  host:
    - icu       # [not win]
  run:
    - icu       # [not win]

about:
  home: http://xerces.apache.org/xerces-c/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Xerces-C++ is a validating XML parser written in a portable subset of C++

extra:
  recipe-maintainers:
    - gillins
    - groutr
    - ocefpaf
